language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 'io.js'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-babel-webpack-boilerplate' ]; then cd .. && eval "mv $currentfolder generator-babel-webpack-boilerplate" && cd generator-babel-webpack-boilerplate; fi